esptool.py
The NodeMCU dev-kit board has a similar auto-reset circuit to previous
ones (RTS drives reset, DTR drives GPIO0), but with a quirk - if both
RTS & DTR are asserted at once, neither nRESET nor GPIO0 are asserted.
This commit changes the reset order so RTS,DTR are asserted one at a
time instead of simultaneously. This should still work with the
traditional configuration as well.
This problem was mentioned in #26.
=> Auto-reset support for NodeMCU devkit as well as esprog,etc.

esptool.py
These changes are mostly based on a discussion I had with @markusgritsch regarding 88baa738a5b7ee5 (PR #30). Lots of discussion in that commit thread.
The first commit here should improve the reliability of auto-resets (using either the "standard" or the NodeMCU reset scheme).
The second commit helps avoid something that is probably unique to Linux, where the CH340 doesn't always switch baud rates like it should - resulting in random slow uploads at times. This shouldn't have any side effects on other OSes.
Thanks for all your work on esptool. :)
=> More auto-reset improvements

esptool.py
Hi,
Just another minor tweak from me. I run into this when running parallel builds of an esp firmware (the two elf2image commands run simultaneously).
Cheers,
Angus
***
Allows two elf2image commands to be run in parallel (ie parallal
make process).
=> Make elf2image command thread-safe

esptool.py
I originally made these changes for the NodeMCU project. Most notably it works around the issue where the flash ends up in write-protect mode when DIO is used, and as such fixes https://github.com/themadinventor/esptool/issues/40. The hows and whys are already referenced within that thread by Marcel.
The second change is to make esptool extract the actual entry point from the ELF file rather than assume a hardcoded call_user_start.
=> Workaround for DIO write protect issue, automatic entrypoint extraction

esptool.py
This is a cleaner rewrite of the code in bug #33 by iggr.  Also added a fake flash_begin so flash_finish returns sucessfully.  See also #48 and #51.
=> workaround for bug in SPIEraseArea

esptool.py
Based on information in #44
Looks like if the kernel thinks the serial port is already set to
[baudrate], it won't set the baud rate in set_termios. Due to the
pre-4.0 bug of always chosing 9600 baud on open, it's possible for the
device to be set to 9600 but the kernel thinks it's set much faster.
Not sure what I was thinking with the other fix in de97c54a0. It did
seem a bit more reliable but possibly this was because when testing I
kept changing the baud rate(!)
=> Better fix for CH341 slow baud rate bug (closes #44)

esptool.py
There're various reports of various port baud speeds non-working (or
working), show actual write speed should provide more insight into
that.
=> write_flash: Show actual flash write speed.

esptool.py
So it's possible to map flash_size directly from Arduino´s `platform.txt` file (which prints out an upper case M):
--flash_size {build.flash_size}
=> Make flash_size option for write_flash case insensitive

esptool.py
Newer ESP modules use a different OUI (5c:cf:7f) which can be accessed from
the MAC3 field in the OTP. When this field is non-zero, it must be used
to form the complete MAC address.
=> Fixed read_mac for recent ESP modules.

esptool.py
This patch makes it possible to verify large firmwares from a Raspberry Pi 2 too. Previously the overhead of reading a single byte at a time (going all the way into the kernel and back) made it impossible to verify at 230400 baud rate, and at 115200 it put a core at ~90%. With this patch, a verify at 230400 is both possible and only uses ~30% cpu.
Patch by @umisef (with white-space cleanup by yours truly).
=> Use bulk reads to massively reduce overheads.

esptool.py
People flashing images particularly Micropython which has recently passed 512k in size using the default flash size are upset when esptool appears to work but in reality doesn't work as intended.
At a minimum warn the user about it. Perhaps it should stop there and then instead.
=> Warn when data does not fit in flash

README.md, esptool.py
If --flash_size=detect (new default) is given, a FlashID will be read, and
Flash size to put into a firmware header will be calculated based on it
(one subfield of FlashID is power-of-2 of the chip capacity, and most modern
chips follow this convention).
=> write_flash: Default to auto-detect Flash size based on ID.

esptool.py
This change allows ports to be opened locally and remote (for example using RFC2217, but also other messaging protocols may be used).
see http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.serial_for_url for details
It's useful if the compiling instance does not have direct serial port access to deploy the firmware (e.g. if you are within a docker container). 
serial_for_url is backward compatible to the existing Serial() call.
=> esptool: use serial_for_url instead of Serial

esptool.py
Interprets process outputs as UTF-8 strings since the symbols used in `get_symbol_addr()` are expected to be utf, as invoked in `elf2image()`.
@projectgus  Based off master this time.
=> Convert process output encodings from bytes to UTF-8

esptool.py
The current read_mac function in esptool is not returning the same MAC address as: ```esp_wifi_get_mac(WIFI_IF_STA, ...)```. It's only returning the last 4 bytes of the MAC address combined with the CRC at the end.
=> Fix read_mac function for the ESP32

README.md, esptool.py
Resolves issue #136 
- Attempts normal connections, then attempts legacy connections
- Improves legacy connection compatibility
- Doesn't slow down non-legacy connect time
I've tested this in Windows (in MSYS2 latest as well as as a compiled .exe with Arduino-ESP32 in Arduino - it worked equally well with both). Note that I used the latest Silicon Labs and FTDI drivers for the respective boards, without enumeration mode.
I tested against the Core Board v2 and the ESP-WROVER-KIT. In both cases the time to connect was minimal for the given board (since the Core Board requires the delay it takes longer to connect to, but since its attempt is always first the WROVER-KIT board connects quickly as normal).
The net effect is that the Core Board v2 can finally be reliably flashed now via Windows …
=> Resolved serial flash issues for legacy devices

README.md
I briefly scanned the README but didn't find any other 1.x references.
=> Remove note about latest stable not supporting ESP32

espefuse.py, espsecure.py
Previously a traceback was shown instead.
Fixes https://github.com/espressif/esptool/issues/211
=> Display usage information when no arguments are provided

esptool.py
Both these functions return a named tuple as well.
=> inspect.getargspec() is depreciated for Py3. 

README.md
4MB-c2 was removed via this commit:
https://github.com/espressif/esptool/commit/eff0e967963470ae88e62dc1d4d15a67f9d63b2a
This is purely a documentation change.
=> Remove unsupported flash size 4MB-c2 from README.md.

esptool.py
Print the MAC address when programming - This is useful when you need to keep track of multiple modules being flashed.
Windows 7, Python3.6, ESP32-WROOM
=> Print MAC before programming

espefuse.py, esptool.py
We have a board designed which has the UART to the ESP32 as a passthrough from
another microcontroller.  As such, it's easier to send the sync sequence and
change the baud rate on the microcontroller side of things than to pass this
change through from the PC.  Adding the --no-sync option allows the intermediate
microcontroller to run the sync sequence and to set the appropriate baud rate
on the ESP32 side of things.  For this use case, we need to avoid sending the
change buad rate sequence (the PC baud rate is not necessarily the same as
the microcontroller <-> ESP32) and avoid sending the sync sequence.
Signed-off-by: Tim Nordell <tim.nordell@nimbelink.com>
=> esptool: Add new argument "--no-sync" to skip sync and initial baud

esptool.py
Assign `None` to `esp` variable in `main()` function. 
`esp` variable was not assigned before the loop, and in case if there were no serial ports detected, the following exception was raised:
```python
esptool.py v2.4.1
Found 0 serial ports
Traceback (most recent call last):
File "c:\dev\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\dev\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Dev\Anaconda3\Scripts\esptool.exe\__main__.py", line 9, in <module>
File "c:\dev\anaconda3\lib\site-packages\esptool.py", line 2814, in _main
main()
File "c:\dev\anaconda3\lib\site-packages\esptool.py", line 2529, in main
if esp is None:
UnboundLocalError: local variable 'esp' referenced before assignment
```
=> Add `esp` variable assigment

README.md, esptool.py
=> Document passing arguments to main()

.travis.yml
Python 3.4 has reached its end of life. https://devguide.python.org/devcycle/#end-of-life-branches
Also, [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"
(Please delete any lines which don't apply)
(Please put issue URLs or #number-of-issue here.)
(Operating system(s), development board name(s), ESP8266 and/or ESP32.)
(Details here: https://github.com/espressif/esptool/blob/master/CONTRIBUTING.md#automated-integration-tests )
=> Travis CI: Drop EOLed Python 3.4 and add Python 3.7

espefuse.py
Addition to get efuse value as JSON object for further processing
Linux, ESP32, WROOM, WROVER
This allow to get efuse value so script can flash devices appropriately depending on secure boot or flash encryption state of the device.
=> ESP Efuse : Get selected efuse value as JSON object

esptool.py
Updating one of my projects I was happy to find python 3 is now supported.
There is a bare  print in esptool.py that needs to be converted to print()
=> Minor python3 fix: bare print -> print()

esptool/loader.py
Silence the traceback that was being printed in such cases,
provide a user-friendly message and finish the app with sys.exit()
instead.
#750 
Fedora Linux 35 - ESP8266
`test_imagegen.py` - OK
`./test_esptool.py /dev/ttyUSB2 esp8266 460800`
I've got this error but I think it's unrelated to my changes.
```
ERROR [6.734s]: test_stub_reuse_with_synchronization (__main__.TestStubReuse)
Keep the flasher stub running and reuse it the next time.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/ksurma/dev/esptool/test/./test_esptool.py", line 603, in test_stub_reuse_with_synchronization
res = self.run_esptool(
File "/home/ksurma/dev/esptool/test/./test_esptool.py", line 199, in run_esptool
raise e
File …
```
=> Gracefully finish esptool when device is not detected on given port (ESPTOOL-468)

esptool/targets/esp32c3.py
Info from get_chip_features is missing "BLE" for the C3
=> C3 has BLE as feature (ESPTOOL-501)

espsecure/__init__.py
The espsecure tool is currently very slow at encrypting large files with AES-XTS. The code currently runs in $O(n^2)$ time complexity, which is very bad.
Some timing I did on my computer:
| Size  | Time |
| ------------- | ------------- |
| 1 MByte | 0.514s  |
| 2 MByte | 1.973s  |
| 4 MByte | 8.806s |
| 8 MByte | 37.318s |
With this patch, these are the new results:
| Size  | Time |
| ------------- | ------------- |
| 1 MByte | 0.146s  |
| 2 MByte | 0.228s  |
| 4 MByte | 0.391s |
| 8 MByte | 0.572s |
```
.......................
----------------------------------------------------------------------
Ran 23 tests in 2.970s
OK
```
=> espsecure: Run AES-XTS encryption in O(n) instead of O(n^2) time complexity (ESPTOOL-523)

espressif/efuse/base_fields.py, espressif/efuse/base_operations.py, espressif/efuse/emulate_efuse_controller_base.py, espressif/efuse/esp32c2/emulate_efuse_controller.py, setup.py, test/test_espefuse_host.py
This is a request to backport https://github.com/espressif/esptool/commit/ee27a6437576797d5f58c31e1c39f3a232a71df0 to the v3 branch.
I am updating `bitstring` in [nixpkgs](https://github.com/NixOS/nixpkgs) to v4.0.1 and would like to depend on it everywhere. nixpkgs packages both esptool v3 and v4 because (it seems) `esphome` still depends on v3.
Thank you!
=> [backport] fix(espefuse): Fix compatibility with Bitstring>=4 (ESPTOOL-552)

docs/en/espsecure/index.rst
The example argument uses `--hsm_config`, but the script itself uses `--hsm-config`
https://github.com/espressif/esptool/blob/0791f7c69fabaf84dcd76da91e548e22f4e9a83a/espsecure/__init__.py#L1500-L1505
Tested `python espsecure.py sign_data --version 2 --hsm --hsm-config <hsm_config_file> --output <signed_image> <datafile>`
=> Fix invalid argument for hsm-config in documentation (ESPTOOL-617)

flasher_stub/Makefile
I'm trying to resume work that I started a few years ago (see #499, #500, #501, [Debian bug #948096](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948096)) to try to have Debian ship the esptool flasher stubs.
The TL;DR is that packages in Debian need to build from source and cannot ship binary blobs, and that includes both the stub binaries, as well as precompiled toolchains. Therefore the current Debian maintainer has opted into removing the stubs entirely. (The package is also a bit stagnated, currently at v2.8, and I'm trying to fix that).
For the RISC-V chips, there is no riscv32-esp-elf-gcc compiler in Debian (obviously :), but riscv64-unknown-elf-gcc (`riscv64-unknown-elf-gcc (12.1.0-7+11) 12.1.0`) exists, and picolibc supports RISC-V as well. What is required on a recent …
=> flasher_stub: pass -mabi=ilp32, add EXTRA_CFLAGS, to allow building with a stock compiler (ESPTOOL-643)

esptool/targets/esp32c6.py
The current implementation appears to be reading the package version and chip version from the wrong efuse bits. Based on [`efuse_reg.h`](https://github.com/espressif/esp-idf/blob/ab63aaa4a24a05904da2862d627f3987ecbeafd0/components/soc/esp32c6/include/soc/efuse_reg.h#L709) and [`esp_efuse_table.csv`](https://github.com/espressif/esp-idf/blob/ab63aaa4a24a05904da2862d627f3987ecbeafd0/components/efuse/esp32c6/esp_efuse_table.csv#L139), this pull request addresses the issue.
https://github.com/espressif/esptool/issues/866
* macOS 13.2.1 (22D68)
* Python 3.11.2
* ESP32-C6-DevKitM-1 V1.0
=> fix(ESP32-C6): Fix get_pkg_version and get_{major,minor}_chip_version (ESPTOOL-657)

docs/en/advanced-topics/serial-protocol.rst
Fixes misspelling of `triggered` in serial protocol docs.
=> Fix typo in serial protocol docs (ESPTOOL-667)

esptool/cmds.py, test/test_image_info.py
Add some additional decoding for the image_info command.
Linux.  image_info doesn't interact with boards.
=> Image info stuff (ESPTOOL-675)

esptool/loader.py
Fixes the detection of USB-JTAG-Serial on ports COM10 and greater due to incorrect PID retrieval.
Commit https://github.com/espressif/esptool/commit/00f4bc967c94b25e3190ebc007a0bf132ae42f02 introduced a bug which changed port names to be matched by `in` when not running on darwin, this means `_get_pid` can instead return the PID for `COM1` instead of `COM10` - `COM19`.
=> Fix USB-JTAG-Serial PID detection error (ESPTOOL-682)

esptool/loader.py, flasher_stub/wrap_stub.py, test/test_espefuse.py, test/test_image_info.py
Fixes the wrong usage of os specific directory separators
OS: macOS, Windows
development board: ESP8266
=> fix: inconsistent usage of dirs separator (ESPTOOL-689)

esp_rfc2217_server.py
add hard reset functionality to rfc2217 server and modify bootloader reset to trigger on DTR_ON instead of RTS_ON. This modification allows to use a rfc2217 server with idf_monitor and other compatible serial monitoring tools. 
I'm not a python or rfc2217 expert and was assuming the default reset sequence, so there could be some issues with custom sequences.
#892
I have tested esp_rfc2217_server.py on windows10 and Ubuntu 22.04.2 LTS using custom esp32-wroom-32 board with the usual automatic bootloader circuit.  
NO TESTING
=> add hard reset to rfc2217 server (ESPTOOL-760)

esptool/uf2_writer.py
This is not a script, so there' no need for it.
I package esptool for Fedora Linux. Our automation has complained that there's a shebang in a file that's not executable. 
Upon inspection it seems so - this file is not intended to be executed directly, hence my proposal to remove the shebang from the file.
NO TESTING
=> Remove the shebang from uf2_writer.py (ESPTOOL-781)

espsecure/__init__.py
The espsecure.py script displays a ResourceWarning error regarding unclosed files when `PYTHONWARNINGS="all"` turns on. This issue arises because espsecure.py utilizes argparse.FileType, which opens a file handler but Python does not automatically handle the close() operation.
``` python
% PYTHONWARNINGS="all" espsecure.py sign_data --version 1 --keyfile keys.pem  --output signed.bin input.bin
espsecure.py v4.7.0
Signed 1032336 bytes of data from input.bin
/dev/.venv/lib/python3.11/site-packages/espsecure/__init__.py:1828: ResourceWarning: unclosed file <_io.BufferedReader name='keys.pem'>
main()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/dev/.venv/lib/python3.11/site-packages/espsecure/__init__.py:1828: ResourceWarning: unclosed file <_io.BufferedReader …
```
=> fix: close file gracefully in espsecure (ESPTOOL-804)

docs/en/esptool/flashing-firmware.rst
Updated the text in this file to fix a typo which was decives, that is now devices.
So sorry about the multiple PRS, I'm not fully up to date with good git practices.
n/a
NO TESTING
NO TESTING
=> docs(flashing): Fixed a typo in /docs/en/esptool/flashing-firmware.rst (ESPTOOL-852)

docs/en/esptool/advanced-options.rst, esptool/__init__.py
Enables user to specify --usbVid and/or --usbPid, which filter the com port list before checking for ESP chips. With many serial ports on the computer, this greatly speeds up the process of esptool identifying the correct com port by allowing esptool to skip all com ports without a matching VID/PID. Implements https://github.com/espressif/esptool/issues/987
NO TESTING ON MAC/LINUX. Tested on Windows64 with ESP32-S3-DevKitC and custom ESP32-S3 board.
```
$ time esptool read_flash_status
esptool.py v4.7.0
Found 4 serial ports
Serial port COM30
Connecting......................................
COM30 failed to connect: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html …
```
=> feat(esptool): allow filtering ports by VID/PID (ESPTOOL-878)

.github/workflows/dev_release_esptool_pypi.yml, .github/workflows/release_esptool_pypi.yml
https://github.com/espressif/esptool/commit/eacc94a386267ad39de876f29b7bd1a6823387ae changed from using 
python setup.py sdist 
to 
python -m build
The latter now builds a .whl which got uploaded using twine on the 4.8.0 release (https://pypi.org/project/esptool/4.8.0/#files)
Unfortuatnely due to setup.py (https://github.com/espressif/esptool/blob/master/setup.py),
the whl that is built on ubuntu uses scripts instead of entry_points
This makes the whl incompatible with Windows systems and causes import error / no exe's created
See https://github.com/espressif/esptool/issues/1010
This change adds --sdist argument to build which tells it not to create the whl.
This allows all systems to just use the source and then do the correct setup.py behaviour …
=> ci(pypi_release): Use build --sdist argument to avoid building non-universal whl (ESPTOOL-926)

pyproject.toml
When running the wheel build of esptool 4.8.0 in Fedora, the `docs/en/conf.py` and `test/efuse_scripts/*.py` were included in the distribution.
Apparently, setuptools excludes only the first level of modules, unless specified otherwise. Following the official documentation, the `Important` part, adding asterisks to exclude all the found submodules does the trick
https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages
I've tested it during the Fedora RPM build and verified this change works for us.
=> [packaging] Exclude also the submodules of test and docs (ESPTOOL-927)

test/test_espefuse.py
This fixes the upcoming issue with Python 3.14: the changed output of argparse help, which will newly print out the program name rather than the name of the file, `__main__.py`.
#1054
NO TESTING
NO TESTING
=> Expect the correct module name for Python's 3.14 argparse output (ESPTOOL-997)

esptool/bin_image.py
The program header table can describe zero or more segments. However, commit ca16d5f3 introduced checks in _read_segments() that will fail on a zero number of program header entries.
ELF files created by objcopy based on a binary file may not have any segments / program header table. The number of program header entries e_phnum in the ELF header is zero.
This was fine before commit ca16d5f3, but is currently broken and esptool will exit with this error:
`A fatal error occurred: No segment header found at offset 0000 in ELF file.`
This PR reinstates the possibility of having no such entries by simply returning early and skip these checks in _read_segments() if e_phnum is zero.
The change has no implication if the number of entries is non-zero.
Tested with ELF files created by objcopy that …
=> fix(esptool): Allow ELF files without segments again (ESPTOOL-1132)
